spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}

  ai:
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}
        project-id: ${GOOGLE_PROJECT_ID}
        embedding:
          api-key: ${GOOGLE_GENAI_API_KEY}
          project-id: ${GOOGLE_PROJECT_ID}

  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      credentials:
        encoded-key: ${GCP_STORAGE_CREDENTIALS}

  jpa:
    show-sql: false

app:
  jwt:
    secret: ${JWT_SECRET}
  auth:
    redirect-success: http://localhost:3000/auth/kakao/callback
    redirect-failure: http://localhost:3000/auth/kakao/failure

gcp:
  storage:
    bucket-name: ${GCP_STORAGE_BUCKET_NAME}
    signed-url-expire-minutes: ${GCP_SIGNED_URL_EXPIRE_MINUTES:15}

logging:
  level:
    root: INFO
    com.chaean.teamchatsa: INFO

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
    enabled: ${SLACK_ALERT_ENABLED}
  alert:
    channel: "#alert"
    username: "TeamChatSa Bot"
    icon-emoji: ":rotating_light:"