global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: home-node-exporter
    static_configs:
      - targets:
          - chaean00.duckdns.org:9100

  - job_name: home-cadvisor
    static_configs:
      - targets:
          - chaean00.duckdns.org:8081

  - job_name: teamchatsa-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - chaean00.duckdns.org:8080

  - job_name: home-postgres-exporter
    static_configs:
      - targets:
          - chaean00.duckdns.org:9187
