SET search_path TO app, public;

CREATE TABLE IF NOT EXISTS feedback
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_user_id BIGINT                      NOT NULL,
    sender_name    VARCHAR(50)                 NOT NULL,
    content        VARCHAR(1000)               NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX idx_feedback_sender_user_id
    ON feedback (sender_user_id, created_at DESC);

COMMENT ON TABLE feedback IS '마이페이지에서 개발자에게 보내는 의견 저장 테이블';
COMMENT ON COLUMN feedback.sender_user_id IS '의견을 보낸 사용자 ID';
COMMENT ON COLUMN feedback.sender_name IS '의견을 보낸 사용자 이름 또는 닉네임 스냅샷';
