CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    nickname VARCHAR(50) NULL UNIQUE,
    email VARCHAR(100) NULL UNIQUE,
    phone VARCHAR(50) NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    role VARCHAR(16) NOT NULL,
    position VARCHAR(8) NOT NULL,
    CONSTRAINT user_role_check CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT user_position_check CHECK (position IN ('GK', 'CB', 'LCB', 'RCB', 'LB', 'RB', 'LWB', 'RWB', 'CDM', 'CM', 'CAM', 'LM', 'RM', 'LW', 'RW', 'CF', 'LF', 'RF', 'ST','LS', 'RS', 'ALL'))
);

CREATE TABLE IF NOT EXISTS "team" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leader_user_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    area VARCHAR(50) NOT NULL,
    description TEXT NULL,
    contact_type VARCHAR(30) NOT NULL ,
    CONSTRAINT team_contact_type_check CHECK (contact_type IN ('EMAIL','PHONE', 'KAKAO')),
    contact VARCHAR(50) NOT NULL,
    level VARCHAR(20) NOT NULL,
    img TEXT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS "team_member" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT team_member_role_check CHECK (role IN ('MEMBER','CO_LEADER','LEADER')),

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "team_application" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    team_id BIGINT NOT NULL ,
    user_id BIGINT NOT NULL ,
    status VARCHAR(30) NOT NULL ,
    CONSTRAINT team_application_status_check CHECK (status IN ('PENDING','ACCEPTED','REJECTED','CANCELLED')),
    message VARCHAR(255) ,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    UNIQUE (team_id, user_id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS "match_post"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id    BIGINT NOT NULL,
    title      VARCHAR(100) NOT NULL,
    content    TEXT NOT NULL,
    match_date TIMESTAMP NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    address VARCHAR(255) NOT NULL,
    place_name VARCHAR(120),

    -- 편의용
    location GEOGRAPHY(POINT, 4326)
        GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geometry) STORED,

    status VARCHAR(8) NOT NULL DEFAULT 'OPEN',
    accepted_application_id BIGINT NULL ,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT match_post_status_check CHECK (status IN ('OPEN','CLOSED'))
);

CREATE TABLE IF NOT EXISTS "match_application" (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id           BIGINT NOT NULL,
    applicant_team_id BIGINT NOT NULL,
    message           TEXT,
    status            VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT match_application_status_check CHECK (status IN ('PENDING','ACCEPTED','REJECTED','CANCELLED'))
)