DROP TYPE IF EXISTS role_type CASCADE ;
DROP TYPE IF EXISTS position_type CASCADE ;
DROP TYPE IF EXISTS match_post_status CASCADE ;
DROP TYPE IF EXISTS match_application_status CASCADE ;

CREATE TYPE role_type AS ENUM ('LEADER', 'PLAYER');
CREATE TYPE position_type AS ENUM ('GK', 'CB', 'LCB', 'RCB', 'LB', 'RB', 'LWB', 'RWB', 'CDM', 'CM', 'CAM', 'LM', 'RM', 'LW', 'RW', 'CF', 'LF', 'RF', 'ST','LS', 'RS');
CREATE TYPE match_post_status AS ENUM ('OPEN','CLOSED');
CREATE TYPE match_application_status AS ENUM ('PENDING','ACCEPTED','REJECTED','CANCELLED');

CREATE OR REPLACE FUNCTION set_updated_at()
    RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NULL,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    role role_type NOT NULL
);

CREATE TABLE IF NOT EXISTS "team" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    area VARCHAR(50) NOT NULL,
    img VARCHAR(255) NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    leader_user_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "team_member" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    position position_type NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    is_deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "match_post"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id    BIGINT NOT NULL,
    title      VARCHAR(100) NOT NULL,
    content    TEXT NOT NULL,
    match_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    place_name VARCHAR(120),

    -- 편의용
    location GEOGRAPHY(POINT, 4326)
        GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography) STORED,

    status match_post_status NOT NULL DEFAULT 'OPEN',
    accepted_application_id BIGINT NULL ,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    is_deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "match_application" (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id           BIGINT NOT NULL,
    applicant_team_id BIGINT NOT NULL,
    message           TEXT,
    status            match_application_status NOT NULL DEFAULT 'PENDING',
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
)