CREATE TABLE IF NOT EXISTS "oauth_account" (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT         NOT NULL,
    provider            VARCHAR(16) NOT NULL,
    provider_user_id    VARCHAR(100)   NOT NULL,
    email_from_provider VARCHAR(100),
    profile_nickname    VARCHAR(100),
    profile_image_url   VARCHAR(255),
    connected_at        TIMESTAMP      NOT NULL DEFAULT now(),
    disconnected_at     TIMESTAMP,
    created_at          TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP      NOT NULL DEFAULT now(),
    is_deleted          BOOLEAN        NOT NULL DEFAULT false,
    CONSTRAINT provider_check CHECK ( provider IN ('KAKAO') )
)