DO $$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM pg_type WHERE typname = 'oauth_provider') THEN
            CREATE TYPE oauth_provider AS ENUM ('KAKAO');
        END IF;
END $$;

CREATE TABLE IF NOT EXISTS "oauth_account" (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT         NOT NULL,
    provider            oauth_provider NOT NULL,
    provider_user_id    VARCHAR(100)   NOT NULL,
    email_from_provider VARCHAR(100),
    profile_nickname    VARCHAR(100),
    profile_image_url   VARCHAR(255),
    connected_at        TIMESTAMP      NOT NULL DEFAULT now(),
    disconnected_at     TIMESTAMP,
    created_at          TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP      NOT NULL DEFAULT now(),
    is_deleted          BOOLEAN        NOT NULL DEFAULT false
)