-- 알림 테이블 생성
CREATE TABLE IF NOT EXISTS notification
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(500) NOT NULL,
    link VARCHAR(255),
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT notification_type_check CHECK (type IN (
       'TEAM_APPLICATION',
       'TEAM_APPLICATION_ACCEPTED',
       'TEAM_APPLICATION_REJECTED',
       'MATCH_APPLICATION',
       'MATCH_APPLICATION_ACCEPTED',
       'MATCH_APPLICATION_REJECTED'
    ))
);

-- 인덱스 생성
CREATE INDEX idx_notification_recipient_is_read
    ON notification (recipient_id, is_read, created_at DESC);

COMMENT ON TABLE notification IS '알림 테이블 - 사용자가 오프라인이어도 저장됨';
COMMENT ON COLUMN notification.recipient_id IS '수신자 User ID';
COMMENT ON COLUMN notification.is_read IS '읽음 여부 (false: 읽지 않음, true: 읽음)';