services:
  postgres:
#    image: postgres:17-alpine
    image: postgis/postgis:17-3.4-alpine
    container_name: "${PROJECT_NAME}-postgresql"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - tcs
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    container_name: "${PROJECT_NAME}-redis"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - tcs
    restart: unless-stopped

  mongodb:
    image: mongo:7.0-jammy
    container_name: "${PROJECT_NAME}-mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      TZ: ${TZ}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tcs
    restart: unless-stopped

volumes:
  pg_data:
  redis_data:
  mongo_data:


networks:
  tcs:
    driver: bridge